# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight UTC
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Change to src directory
      run: cd src 
    - name: Restore dependencies
      run: dotnet restore LastChristmas.sln
    - name: Build
      run: dotnet build --no-restore
    - name: Execute
      run:  dotnet run -c Release --project LastChristmas.Console $GITHUB_WORKSPACE/publish_pages --md --html
      
    
